export const typeColors: Record<string, string> = {
  normal: "bg-zinc-700 text-white dark:bg-zinc-300 dark:text-black",
  fire: "bg-orange-700 text-white dark:bg-orange-600 dark:text-white",
  water: "bg-blue-700 text-white dark:bg-blue-600 dark:text-white",
  grass: "bg-emerald-700 text-white dark:bg-emerald-600 dark:text-white",
  electric: "bg-yellow-500 text-black dark:bg-yellow-400 dark:text-black",
  ice: "bg-cyan-600 text-black dark:bg-cyan-300 dark:text-black",
  fighting: "bg-red-700 text-white dark:bg-red-600 dark:text-white",
  poison: "bg-purple-700 text-white dark:bg-purple-600 dark:text-white",
  ground: "bg-amber-800 text-white dark:bg-amber-600 dark:text-white",
  flying: "bg-indigo-600 text-white dark:bg-indigo-500 dark:text-white",
  psychic: "bg-pink-700 text-white dark:bg-pink-600 dark:text-white",
  bug: "bg-lime-700 text-white dark:bg-lime-500 dark:text-black",
  rock: "bg-stone-700 text-white dark:bg-stone-400 dark:text-black",
  ghost: "bg-violet-800 text-white dark:bg-violet-600 dark:text-white",
  dragon: "bg-indigo-800 text-white dark:bg-indigo-600 dark:text-white",
  dark: "bg-zinc-800 text-white dark:bg-zinc-200 dark:text-black",
  steel: "bg-slate-600 text-white dark:bg-slate-400 dark:text-black",
  fairy: "bg-pink-500 text-white dark:bg-pink-300 dark:text-black",
};
